### ISSUE TITLE
delete part bake-select problem-collision

### ISSUE THREAD

**Issue by xie-ya** [MiniEval/Bone-Physics#11]
1. I want to know how to delete some of these baked boxes. According to the plug-in instructions, there is no corresponding box name in the plug-in list on the right side of the selected bone.

2. Also, when you create a box for the first time, you cannot select all the box names in the sidebar of the plug-in, nor can you select them.

3. The hair and the body are two parts respectively. If I paint pin weight of the vertex group, do I need to set the body as the target set of collision to prevent the mold from piercing?

**Comment by xie-ya** [comment]
![屏幕截图 2023-09-07 121111](https://github.com/MiniEval/Bone-Physics/assets/128943605/d74c7d59-0956-4766-a4fa-78b53c807b91)

**Comment by MiniEval** [comment]
1. Delete box mesh, remove pose constraints on relevant joints.
2. The sidebar selections are not designed to be one-to-one with native object selections, because the plugin is designed to work in the edit/pose mode of an active armature. You can edit them in the viewport independently if you wish.
3. This is not the place to ask about how collision setups should be designed.

**Comment by xie-ya** [comment]
1.0 How to select all the bones with collision boxes at one time? This button is not available in the sidebar of this plug-in.
1.1 How to delete the same constraint of the selected bones at one time without deleting other constraints on the selected bones?
3. Setting collision objects directly on the body has poor effect. Excuse me, do you have any corresponding tutorial recommendations?

**Comment by xie-ya** [comment]
> 1. 删除箱形网格，去除相关关节的姿势约束。
> 2. 侧边栏选择不是与本机对象选择一对一的，因为该插件设计为在活动骨架的编辑/姿势模式下工作。如果您愿意，可以在视口中独立编辑它们。
> 3. 这里不是询问应该如何设计碰撞设置的地方。

1.0 How to select all the bones with collision boxes at one time? This button is not available in the sidebar of this plug-in.
1.1 How to delete the same constraint of the selected bones at one time without deleting other constraints on the selected bones?
3. Setting collision objects directly on the body has poor effect. Excuse me, do you have any corresponding tutorial recommendations?

**Comment by MiniEval** [comment]
> > 1. 删除箱形网格，去除相关关节的姿势约束。
> > 2. 侧边栏选择不是与本机对象选择一对一的，因为该插件设计为在活动骨架的编辑/姿势模式下工作。如果您愿意，可以在视口中独立编辑它们。
> > 3. 这里不是询问应该如何设计碰撞设置的地方。
> 
> 1.0 How to select all the bones with collision boxes at one time? This button is not available in the sidebar of this plug-in. 1.1 How to delete the same constraint of the selected bones at one time without deleting other constraints on the selected bones? 3. Setting collision objects directly on the body has poor effect. Excuse me, do you have any corresponding tutorial recommendations?

1&2. Relevant joints should be in yellow or orange while in pose mode. You should just do this manually. There should not be so many joints as to warrant a script for iteratively removing this specific pose constraint.
![image](https://github.com/MiniEval/Bone-Physics/assets/85723511/fb85527a-8883-4963-a8d4-49b215623bc1)

3. Pin more basic shapes around the body to create a stable collision mesh. If you do not know how to do this, you will need to learn a lot more about Blender and its physics system as a whole.
https://www.youtube.com/watch?v=lctjzasiy64
